services:
#================================================================
# Start Keycloak
#----------------------------------------------------------------
  keycloak:
    # This is kc 24.0.1 with opentdf protocol mapper on board
    image: keycloak/keycloak:25.0
    restart: always
    command: ['start-dev']
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      KC_DB_VENDOR: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_URL_PORT: 5434
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: changeme
      KC_HOSTNAME_PORT: '${PLATFORM_HTTPS_PORT:-8443}'
      KC_HOSTNAME: '${PLATFORM_HOSTNAME}'
      KC_HOSTNAME_STRICT_HTTPS: 'true'
      KC_HTTP_ENABLED: 'false'
      KC_HTTPS_PORT: ${PLATFORM_HTTPS_PORT:-8443}
      KC_HTTP_PORT: 8888
      KC_HTTPS_CERTIFICATE_FILE: '/opt/keycloak/conf/${PLATFORM_HOSTNAME}.pem'
      KC_HTTPS_CERTIFICATE_KEY_FILE: '/opt/keycloak/conf/${PLATFORM_HOSTNAME}.key.pem'
      ### Enable these lines when using x509/PKI Authentication
      # KC_HTTPS_TRUST_STORE_FILE: /etc/x509/https/${PLATFORM_HOSTNAME}.truststore.jks
      # KC_HTTPS_TRUST_STORE_PASSWORD: password
      ### END x509/PKI Authentication
      KC_HTTPS_CLIENT_AUTH: request
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      KC_FEATURES: 'preview,token-exchange'
      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8888:8888'
      - '${PLATFORM_HTTPS_PORT:-8443}:${PLATFORM_HTTPS_PORT:-8443}'
    healthcheck:
      test: ['CMD-SHELL', 'echo > /dev/tcp/localhost/${PLATFORM_HTTPS_PORT:-8443}']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 2m
    volumes:
      - ../dsp-keys/${PLATFORM_HOSTNAME}.pem:/opt/keycloak/conf/${PLATFORM_HOSTNAME}.pem
      - ../dsp-keys/${PLATFORM_HOSTNAME}.key.pem:/opt/keycloak/conf/${PLATFORM_HOSTNAME}.key.pem
      ### Enable these lines when using x509/PKI Authentication
      # - ../dsp-keys:/etc/x509/https/
      # - ../dsp-keys/${PLATFORM_HOSTNAME}.truststore.jks:/etc/x509/https/${PLATFORM_HOSTNAME}.truststore.jks
      ### END x509/PKI Authentication
    network_mode: host


